### ISSUE TITLE
Doesn't work with aternos servers

### ISSUE THREAD

**Issue by MrDioVkrad** [ToBinio/visible-entities#5]
The mod does not work on Aternos servers; when you try to log in with it, it gives the following error: 
---- Minecraft Network Protocol Error Report ----
// All lines are down!

Time: 2024-12-30 22:00:21
Description: Packet handling error

java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because the return value of "java.util.Map.get(Object)" is null
	at knot//net.minecraft.class_2370.method_40263(class_2370.java:394)
	at java.base/java.util.HashMap.forEach(HashMap.java:1429)
	at knot//net.minecraft.class_2370.method_40257(class_2370.java:385)
	at knot//net.minecraft.class_6864$class_5748.method_56532(class_6864.java:85)
	at knot//net.minecraft.class_9175.method_56592(class_9175.java:31)
	at java.base/java.util.HashMap.forEach(HashMap.java:1429)
	at knot//net.minecraft.class_9175.method_56591(class_9175.java:29)
	at knot//net.minecraft.class_9175.method_57053(class_9175.java:41)
	at knot//net.minecraft.class_9173.method_56585(class_9173.java:70)
	at knot//net.minecraft.class_8674.method_57043(class_8674.java:117)
	at knot//net.minecraft.class_8674.method_57044(class_8674.java:109)
	at knot//net.minecraft.class_8674.method_52794(class_8674.java:117)
	at knot//net.minecraft.class_8733.method_53041(class_8733.java:22)
	at knot//net.minecraft.class_8733.method_11054(class_8733.java:8)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:27)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:121)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1240)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_2370.method_40263(class_2370.java:394)
	at java.base/java.util.HashMap.forEach(HashMap.java:1429)
	at knot//net.minecraft.class_2370.method_40257(class_2370.java:385)
	at knot//net.minecraft.class_6864$class_5748.method_56532(class_6864.java:85)
	at knot//net.minecraft.class_9175.method_56592(class_9175.java:31)
	at java.base/java.util.HashMap.forEach(HashMap.java:1429)
	at knot//net.minecraft.class_9175.method_56591(class_9175.java:29)
	at knot//net.minecraft.class_9175.method_57053(class_9175.java:41)
	at knot//net.minecraft.class_9173.method_56585(class_9173.java:70)
	at knot//net.minecraft.class_8674.method_57043(class_8674.java:117)
	at knot//net.minecraft.class_8674.method_57044(class_8674.java:109)

-- Incoming Packet --
Details:
	Type: clientbound/minecraft:finish_configuration
	Is Terminal: true
	Is Skippable: false
Stacktrace:
	at knot//net.minecraft.class_2600.method_59803(class_2600.java:56)
	at knot//net.minecraft.class_8673.method_60882(class_8673.java:136)
	at knot//net.minecraft.class_8673.method_59807(class_8673.java:113)
	at knot//net.minecraft.class_2600.method_11072(class_2600.java:32)
	at knot//net.minecraft.class_1255.method_18859(class_1255.java:162)
	at knot//net.minecraft.class_4093.method_18859(class_4093.java:23)
	at knot//net.minecraft.class_1255.method_16075(class_1255.java:136)
	at knot//net.minecraft.class_1255.method_5383(class_1255.java:121)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1240)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Connection --
Details:
	Protocol: configuration
	Flow: CLIENTBOUND
	Server type: OTHER
	Server brand: Paper

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 658761560 bytes (628 MiB) / 1207959552 bytes (1152 MiB) up to 22380806144 bytes (21344 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 7735HS with Radeon Graphics        
	Identifier: AuthenticAMD Family 25 Model 68 Stepping 1
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 512.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.12019.1028
	Graphics card #1 name: NVIDIA GeForce RTX 3070
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 8192.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.6636
	Memory slot #0 capacity (MiB): 32768.00
	Memory slot #0 clockSpeed (GHz): 5.60
	Memory slot #0 type: Unknown
	Virtual memory max (MiB): 34043.11
	Virtual memory used (MiB): 18482.04
	Swap memory total (MiB): 2048.00
	Swap memory used (MiB): 41.14
	Space in storage for jna.tmpdir (MiB): available: 101389.65, total: 476129.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 101389.65, total: 476129.00
	Space in storage for io.netty.native.workdir (MiB): available: 101389.65, total: 476129.00
	Space in storage for java.io.tmpdir (MiB): available: 101389.65, total: 476129.00
	Space in storage for workdir (MiB): available: 101389.65, total: 476129.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx21330M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.110.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.0+da19b51a19
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.24+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.0+34f5d91419
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.88+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.2.0+45b9699719
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.1
		sodium: Sodium 0.6.3+mc1.21.1
		visible-entities: Visible Entities 0.1.4+mc1.21.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.2+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.12.0
			com_twelvemonkeys_common_common-io: common-io 3.12.0
			com_twelvemonkeys_common_common-lang: common-lang 3.12.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.12.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.12.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.12.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1

**Comment by ToBinio** [comment]
What exactly is your current setup?

Does the mod crash on the server or on your client?
Is it even installed on the server, or do you have a vanilla server?

I played a round with it a bit and cant seem to cause a crash

**Comment by MrDioVkrad** [comment]
Pure minecraft only with mod and dependencies. 
The PaperMC server is 1.21.1, it has plugins, but this mod is not there.
When I try to log into the server, it simply does not log in and writes this error.

**Comment by ToBinio** [comment]
sry... i still can not reproduce this.
and i am also still a bit confused

Is this being logged on the client or server?

Are you certain that this is connected to my mod since it seems to be some networking issue which my mod (at least on the client) does not do?
Could you also verify if this is in any way connected to athernos itself or to some plugin you have installed on there.

Maybe you have some anti-cheat that has a problem with my mod or fabric it self.

if this is a log message from the client...
could you send the whole log - https://mclo.gs/
